"""Subclass of sample, which is generated by wxFormBuilder."""

import wx
import sample


# Implementing sample
class MyProject2sample(sample.sample):
    def __init__(self, parent):
        sample.sample.__init__(self, parent)
