"""Subclass of Top, which is generated by wxFormBuilder."""

import wx
import sono1


# Implementing Top
class sono1Top(sono1.Top):
    def __init__(self, parent):
        sono1.Top.__init__(self, parent=None)

    # Handlers for Top events.
    def tako(self, event):
        # TODO: Implement tako
        pass

    def talk(self, event):
        # TODO: Implement talk
        pass

    def speech(self, event):
        # TODO: Implement speech
        pass
