"""Subclass of topFrame, which is generated by wxFormBuilder."""

import wx
import tab
from loguru import logger

# Implementing topFrame
class tabTesttopFrame( tab.topFrame ):
	def __init__( self, parent ):
		tab.topFrame.__init__( self, parent )

	def onButton( self, event ):
		logger.debug('button')

	def onDate( self, event ):
		logger.debug('date')

	def tab( self, event: wx.Event ):
		logger.debug('tab')
		logger.debug(event.EventObject.Selection)
